project:
  type: website
  output-dir: docs

website:
  title: "taha6767.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu:
          - text: "TidyTuesday Analysis 1"
            href: tidytuesday1.qmd
          - text: "TidyTuesday Analysis 2"
            href: tidytuesday2.qmd
          - text: "Project 2"
            href: Project2TahaCopy.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
