project:
  type: website
  output-dir: docs

website:
  title: "taha6767.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "My Projects"
        menu:
          - text: "Analyzing Ceo Departures Using R"
            href: tidytuesday1.qmd
          - text: "Draugh Analysis of California Using R"
            href: tidytuesday2.qmd
          - text: "Analyzing Netflix Data Using R"
            href: Project2Taha copy.qmd
          - text: "Simulation of an Hypothetical Situation in R"
            href: Project3Taha.qmd
          - text: "Replicating a Graph in R"
            href: Project4.qmd
          - text: "Presentation on My Projects so Far"
            href: Project5PresentationQMD.qmd
          - text: "RAG Project"
            href: RAG.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
