---
title: "CEO departure analysis"
execute:
  echo: false
---

The data comes from Gentry et al. by way of DataIsPlural. It contains the reasons for CEO departure in S&P 1500 firms from 2000 through 2018. Below the graph is my analysis of the data.

The reason data was collected according to the authors: To create an open-source, transparent database documenting CEO departures and their reasons in S&P 1500 firms

<https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-04-27/readme.md>

```{r message=FALSE, warning=FALSE}
library(tidytuesdayR) 
library(tidyverse) 
library(visdat)

tt <- tidytuesdayR::tt_load('2021-04-27') 
ceo <- tt$departures 
ceo_reduced <- ceo %>% 
   filter(departure_code %in% 3:7) %>% 
   mutate(
      departure_label = as.factor(recode(departure_code,
         `3` = "Bad performance",
         `4` = "Legal",
         `5` = "Retired",
         `6` = "New opportunity",
         `7` = "Other")),
      fyear = lubridate::make_date(fyear)) %>% 
   relocate(fyear, departure_label)

ceo_reduced %>% 
   group_by(departure_label) %>% 
   count() %>% 
   ggplot(aes(y = fct_reorder(departure_label, n), x = n)) + 
   geom_col(fill = "pink") +
   labs(
      title = "CEO depature by reason",
      subtitle = "S&P 1500 firms between 1987 - 2019",
      x = "",
      y = "",
      caption = "Source: Gentry et al."
   ) + 
   scale_x_continuous(breaks = scales::breaks_width(500))

```

-   Retirement is by far the most common reason for CEO departures, accounting for the highest number of cases.

-   "Other" reasons form the second largest category, suggesting that many CEO departures are due to complex or unspecified factors.

-   Bad performance is the third most frequent reason, indicating that a significant number of CEOs leave their positions due to poor company results.

-   Legal issues and new opportunities are the least common reasons for CEO departures, with relatively few cases in each category.

-   The data suggests that natural career progression (retirement) and unspecified factors play a larger role in CEO turnover than forced departures due to performance issues or legal troubles.
